### ISSUE TITLE
Documentation : Single Run command

### ISSUE THREAD

**Issue by bmeurant** [sglanzer/ember-cli-blanket#101]
The single run command from the README file (``ember test --test-page='tests/index.html?coverage'``) does not work for me with ember-cli 1.13.13.

I tried with ths command instead : ``ember test --test_page=tests/index.html?coverage`` and everything is ok. (Note usage of `_` instead of `-` and no quote).

I don't know if this is only a typo or an ember-cli or blanket change.

**Comment by sglanzer** [comment]
Looks like another ember-cli change that breaks us, thanks for the info; we
can update the readme with this

**Comment by bmeurant** [comment]
You're very welcome. 

Thank you for this addon !
