### ISSUE TITLE
Not working with ember-cli 2.2.0-beta.1 & loader.js 3.5.0

### ISSUE THREAD

**Issue by offirgolan** [sglanzer/ember-cli-blanket#102]
`Error parsing instrumented code: TypeError: Cannot read property 'deps' of undefined`

I believe this is because of the new loader implementation. From playing around with some of my code, I noticed that some modules have been renamed once I upgraded.

As an example, I have a check to see if moment exists

```
const moment = self.requirejs.entries['moment'] && self.require('moment')['default'];
```

which failed after upgrading. It had changed to the following

```
const moment = self.requirejs.entries['moment/index'] && self.require('moment')['default'];
```

Honestly, I don't really know if that is what is causing this addon to fail but I have a hunch it is. As of right now, I cant even see the `Enable Coverage` check mark at the top of my tests page.

**Comment by sglanzer** [comment]
The loader is definitely an issue for us currently - I'm hoping for some
help from the ember-cli core team on this, but otherwise I'll try to start
hacking at it myself (I need this as well, just can't guarantee a time
commitment).

Do you see this as different from
https://github.com/sglanzer/ember-cli-blanket/issues/100?

**Comment by offirgolan** [comment]
Well, in #100, at least this somewhat works but beyond that, the coverage doesnt work at all. If you want to merge this into #100, feel free :smile:

**Comment by jschilli** [comment]
I doubt that ember-cli blanket has anything to do with this. If you drop loader.js back to 3.2.1 it resolves the coverage issue. 

Would be interesting to see if it resolves this as well. 

-jeff

**Comment by sglanzer** [comment]
Unfortunately it still has something to do with us, since we'll need to
figure out how to work with new versions of ember-cli

**Comment by lolmaus** [comment]
I've upgraded my project to from Ember CLI 1.13.15 to 2.3.0-beta.1.

For me tests freeze unless I remove `ember-cli-blanket` from `package.json`. Is it the same issue?

**Comment by jschilli** [comment]
Can you retest this with version 0.9.1 (and be sure to update blanket.js via `ember g ember-cli-blanket`) and reopen if it still persists

**Comment by skaterdav85** [comment]
Seems like it works now. Thanks!!
