### ISSUE TITLE
No coverage generated if project name contains the word 'template'

### ISSUE THREAD

**Issue by jagthedrummer** [sglanzer/ember-cli-blanket#109]
If the project name contains the word 'template' ember-cli-blanket ignores every file in the project, and thus doesn't generate any coverage data at all.

It looks like this is due to the default `antifilter` and would also affect projects that happened to have the word 'tests' in the name.

It would be helpful to point this out somewhere very prominently in the docs.

**Comment by jschilli** [comment]
PR's welcome

**Comment by donahchoo** [comment]
@jschilli @sglanzer Is there a reason to not use 

`  antifilter: '//.*(tests|\.hbs$).*/',`
instead?
