### ISSUE TITLE
functions under /utils are always not tested

### ISSUE THREAD

**Issue by rayjcwu** [sglanzer/ember-cli-blanket#114]
I use `ember g Util test-util` to generate some utility files.

the generated files are like

```
export default function testUtil() {
  // my code
}

```

```
import testUtil from 'insights/utils/test-util';
import { module, test } from 'qunit';

module('Unit | Utility | test util');

// Replace this with your real tests.
test('it works', function(assert) {
  // my tests
});

```

but the coverage report always show testUtil() untested, no matter how many tests I wrote. Am I writing in the correct way?

My env is
ember-cli 2.3.0
ember-cli-blanket 2.8.0

**Comment by jschilli** [comment]
Check your blanket options. The exclusion patterns skip coverage on test files. You can either muck with that pattern or rename. 

-jeff

**Comment by rayjcwu** [comment]
Thank you Jeff, but files under /util are not excluded. ember-cli-blanket does go over that file but it always thinks those functions are untested.

![screen shot 2016-02-24 at 9 01 48 pm](https://cloud.githubusercontent.com/assets/4761728/13310321/dbfbe3a2-db39-11e5-8647-68eba0256d73.png)

**Comment by jschilli** [comment]
@rayjcwu fair enough - this sounds to me like it it #100 or #102 

We have a PR ready to merge that resolves this - dropping loader.js back prior to 3.5.0 and see if that resolves it.

**Comment by rayjcwu** [comment]
@jschilli I guess I have to downgrade ember-cli at the same time, because if I downgrade loader.js by itself I got a lot of `Uncaught ReferenceError: define is not defined`

**Comment by svkangal** [comment]
@jschilli I see same issue with adapters too..

**Comment by jschilli** [comment]
See #100 or #102  - this should be resolved with the release of 0.9.x (0.9.0 came out yesterday but has a dependency issue - resolved with #117) - 0.9.1 should be out soon or you can run against master

**Comment by rayjcwu** [comment]
Hi @jschilli, I found 0.9.1 is already on npm, I upgrade `ember-cli-blanket` to `0.9.1` and `blanket` to `1.1.7`. But when I run test, I got a lot of `TypeError: blanket.instrumentSync is not a function(…)`  in `blanket-require.js` and no code coverage results were shown.

**Comment by jschilli** [comment]
`ember g ember-cli-blanket` or `bower i blanket#5e94fc30f2e694bb5c3718ddcbf60d467f4b4d26` will fix it

@rwwagner90 updated the README  - still thinking about startup diagnostics that will fix that

**Comment by rayjcwu** [comment]
Thank you @jschilli , looks good !_!

**Comment by rayjcwu** [comment]
I found some files are skipped after I upgrade ember-cli-blanket, checking I need to tweak some configurations....

**Comment by jschilli** [comment]
@rayjcwu  can we close this now?

**Comment by rayjcwu** [comment]
@jschilli it does scan lines in files under /utils, but some files were missing.

for example, running with the default `blanket-options.js`
```
insights/components/ai-select/row                         // included
insights/components/ai-select/power-select          // missing
insights/components/base-table-module               // missing
```
dozens of files are missing from the code coverage report

**Comment by jschilli** [comment]
@rayjcwu so the missing files - are they not imported during your test run? e.g potentially uncovered

in #127 we're having this discussion about the change since 0.9.0 - I'm thinking about a way to close that gap.

If you can confirm that this is the case, I'll close this issue in favor of a new issue laying out the missing files issue.

**Comment by jschilli** [comment]
should be resolved with #128 - if you can pull and confirm from my branch - that would be helpful

**Comment by rayjcwu** [comment]
it works in my case, thank you @jschilli  :+1:

**Comment by jschilli** [comment]
thanks
