### ISSUE TITLE
lcov.dat not being generated for 0.6.2+ version

### ISSUE THREAD

**Issue by svkangal** [sglanzer/ember-cli-blanket#116]
I am using ember-cli 2.3.0, not sure if that has got to do anything with the issue

**Comment by jschilli** [comment]
upgrade to ember-cli-blanket 0.9.1 - be sure to rerun ember g ember-cli-blanket to get updated blanket.js install

**Comment by NullVoxPopuli** [comment]
when I run `ember test --test-page='tests/index.html?coverage'`,  I can't find the lcov file anywhere....

here is my blanket-options.js:

```
/* globals blanket, module */

var options = {
  modulePrefix: 'aeonvera',
  filter: '//.*aeonvera/.*/',
  antifilter: '//.*(tests|template).*/',
  loaderExclusions: [],
  enableCoverage: true,
  cliOptions: {
    reporters: ['json', 'lcov'],
    autostart: true,
    lcovOptions: {
      outputFile: 'lcov.aeonvera.info',
      excludeMissingFiles: true,

      // provide a function to rename es6 modules to a file path
      renamer: function(moduleName) {
        // return a falsy value to skip given module
        if (moduleName === 'unwanted') { return; }

        var expression = /^APP_NAME/;
        return moduleName.replace(expression, 'app') + '.js';
      }
    }
  }
};
if (typeof exports === 'undefined') {
  blanket.options(options);
} else {
  module.exports = options;
}

```

**Comment by svkangal** [comment]
@jschilli  trying out new version

**Comment by svkangal** [comment]
I get the file now but it has 'undefined' in it and nothing else

**Comment by sandersky** [comment]
Seeing the same thing, the `lcov` file is generated but contains no information. If I switch from `lcov` to `json` I see coverage in the file.

**Comment by SSS2557** [comment]
any updates on this? :(

**Comment by sglanzer** [comment]
We fixed this in our projects - you can check https://github.com/ciena-frost/ember-frost-button for an example.  I can't recall exactly what was changed, but @sandersky may remember.

**Comment by SSS2557** [comment]
thanks a lot @sglanzer 

I am guessing the solution is in this:
https://github.com/ciena-frost/ember-frost-button/pull/46/commits/a77ee9e4b8685325bbbfde70fa8d325597436ef8

I will take a look :) 
@sandersky , would be great if you could let me know any other insight.

Appreciate your help

**Comment by acorncom** [comment]
Might be related to #112

**Comment by svkangal** [comment]
@jschilli This has been fixed with new version and can be closed

**Comment by jschilli** [comment]
@svkangal thx
