### ISSUE TITLE
0.9.1 not working in Chrome on Travis

### ISSUE THREAD

**Issue by rwwagner90** [sglanzer/ember-cli-blanket#121]
After updating to the latest, I am getting errors that Travis cannot find blanket. Any ideas?

https://travis-ci.org/shipshapecode/ember-shepherd/jobs/113577589

**Comment by jschilli** [comment]
@rwwagner90 hmmm.  I'm going to suspect timing - I pulled the repo and ran chrome locally fine.  

I'll noodle on it

**Comment by rwwagner90** [comment]
@jschilli yeah chrome works locally. Travis does not throw the error that it cannot find blanket if I use phantom, but it does if I use chrome. I've been having issues with a lot of timing stuff that forced me to use chrome because phantom did not wait for the whole vendor bundle or something.

**Comment by rwwagner90** [comment]
I confirmed this is an issue with ember-cli-blanket because I removed it and blanket and now my tests run without those errors. Please let me know what you need from me to help debug this.

**Comment by sglanzer** [comment]
Is this exclusive to Chrome or do you see the same for Firefox?

**Comment by rwwagner90** [comment]
@sglanzer this is only in Travis. I am running Chrome on Travis to run my tests. You can see the output in the link I posted.

**Comment by sglanzer** [comment]
Right, I use Firefox in Travis - I was just wondering if this was exclusive to Chrome on Travis or more specifically an issue with our bower dependencies in Travis

**Comment by rwwagner90** [comment]
@sglanzer it does appear that Firefox works in Travis https://travis-ci.org/shipshapecode/ember-shepherd/jobs/113889110 . 

Chrome is still messed up, just tried again:

https://travis-ci.org/shipshapecode/ember-shepherd/jobs/113890874

Any ideas? I can switch to Firefox for now, so this doesn't block me from using ember-cli-blanket, but I would love for everything to work in Chrome.

**Comment by sglanzer** [comment]
I guess switch to Firefox for now - interesting that it's literally a browser issue - I use Chrome for all local testing, but Firefox for Travis (because it's installed by default).  I'm afraid I don't have any leads to offer currently, but at least it's a data-point.

**Comment by rwwagner90** [comment]
Yeah, not sure. Since Firefox seems to work fine, it's not that pressing for me personally. I wonder if it just has to do with blanket being a fork. I think it used to work in Chrome on previous versions.

**Comment by rwwagner90** [comment]
Anyone know if this is fixed?

**Comment by sglanzer** [comment]
I haven't looked at it personally and I haven't seen any other reports, so it's unconfirmed currently

**Comment by rwwagner90** [comment]
I'm going to close this, as just using FF is acceptable to me. Feel free to reopen if you'd like to look into getting Chrome to work
