### ISSUE TITLE
I can't get the coverage to generate at all.

### ISSUE THREAD

**Issue by NullVoxPopuli** [sglanzer/ember-cli-blanket#124]
Here is my blanket-options.js

```
/* globals blanket, module */

var options = {
  modulePrefix: 'aeonvera',
  filter: '//.*aeonvera/.*/',
  antifilter: '//.*(tests|template).*/',
  loaderExclusions: [],
  enableCoverage: true,
  cliOptions: {
    reporters: ['lcov'],
    autostart: true,
    lcovOptions: {
      outputFile: 'lcov.ae.info',
      excludeMissingFiles: true,

      // provide a function to rename es6 modules to a file path
      renamer: function(moduleName) {
        // return a falsy value to skip given module
        if (moduleName === 'unwanted') { return; }

        var expression = /^APP_NAME/;
        return moduleName.replace(expression, 'app') + '.js';
      }
    }
  }
};
if (typeof exports === 'undefined') {
  blanket.options(options);
} else {
  module.exports = options;
}

```

and testem

```
{
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed&coverage",
  "disable_watching": true,
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
}

```

I've even tried with 

ember test --test-page='tests/index.html?coverage'

and

ember test --test_page='tests/index.html?coverage'

**Comment by NullVoxPopuli** [comment]
I'm using ember 2.4

**Comment by jschilli** [comment]
What version of ember-cli-blanket?

Do you see results in browser?

-jeff

**Comment by NullVoxPopuli** [comment]
"ember-cli-blanket": "0.9.1",

when I do `ember test --server` I see that Enable Coverage is checked.

and the results are underneath.
(this is good to know, I hadn't tried the server version yet)

but, results don't seem to generate if I just do ember test, or npm run test.

my npm run test does this:
```
    "jscs": "jscs -e app/ --fix && jscs -e tests/ --fix",
    "test": "npm run jscs && ember test"
```

**Comment by NullVoxPopuli** [comment]
oh, I still don't see any generated lcov files or anything in the root directory.

**Comment by jschilli** [comment]
When you run in browser it will still write to the server to generate the file. 

Can you look in the inspector to look for /write-blanket-coverage?  Any errors in console?



-jeff

**Comment by NullVoxPopuli** [comment]
```
Mirage: Your Ember app tried to POST '/write-blanket-coverage', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file. Did you forget to add your namespace?
``` 

oh ok, this is good to check. I thought the mirage thing on the readme was optional. I'll do that real quick.

**Comment by NullVoxPopuli** [comment]
ok, as per Mirage docs, I added

  this.passthrough('/write-blanket-coverage');

now there is no error -- however, I still don't see coverage files :-(

**Comment by NullVoxPopuli** [comment]
here is my repo, if you're curious: https://github.com/NullVoxPopuli/aeonvera-ui

**Comment by jschilli** [comment]
Thx. Will be later before I can take a look

-jeff

**Comment by NullVoxPopuli** [comment]
kk - if there is anything I can do to help give you more information or debug, lemme know

**Comment by akshayrawat** [comment]
For me `ember test --test_page='tests/index.html?coverage'` was ignoring the `--test-page` option. Adding it `&coverage` to `testem.json`'s `test_page` worked.

**Comment by NullVoxPopuli** [comment]
my results:
```
me@Computer 192.168.1.10  ~/Development/aeonvera-ui
⬡ v4.3.1 💎  2.3.0 (master) $ ember test --test_page='tests/index.html?coverage'

... test output ...
me@Computer 192.168.1.10  ~/Development/aeonvera-ui
⬡ v4.3.1 💎  2.3.0 (master) $ ls
app               build-for-rails-dev.sh  ember-cli-build.js  node_modules  production-build-for-rails.sh  testem.json  vendor
bower_components  config                  Gruntfile.js        nvm-setup     public                         tests
bower.json        dist                    LICENSE             package.json  README.md                      tmp

```


what's your `ember version --verbose` give you? here is mine:
```
$ ember version --verbose
version: 2.3.0
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
http_parser: 2.5.2
node: 4.3.1
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2f
os: linux x64
```

**Comment by NullVoxPopuli** [comment]
maybe I'm looking in the wrong folder?

**Comment by akshayrawat** [comment]
```
$ember version --verbose                                                                                                             
version: 1.13.15
http_parser: 2.6.1
node: 5.6.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2f
npm: 2.14.10
os: darwin x64
```

Thats strange, it should have worked.

**Comment by NullVoxPopuli** [comment]
can you try with ember 2.3?

**Comment by jschilli** [comment]
it's definitely mirage blocking the /write-blanket-coverage call

I took ember-cli-mirage out of your project (and commented it out in login-test) ran and got the following:

<img width="504" alt="screen shot 2016-03-08 at 5 15 18 pm" src="https://cloud.githubusercontent.com/assets/122509/13619925/86e5d112-e551-11e5-9adc-e2c61e3818e9.png">

**Comment by jschilli** [comment]
I don't use mirage so I would look @ the doc (including the blanket readme) as to how to support that POST call being valid.

in general, you should be able to see a call to /write-blanket-coverage in the network tab when tests complete.

if you don't something is blocking it (or an error occurred) which should result in something in the console.

**Comment by NullVoxPopuli** [comment]
hmmm. ok, I'll see what I can find out.

**Comment by sglanzer** [comment]
Have you tried a general passthrough? `this.passthrough()`

We have projects using mirage and blanket, with 2.3+ ember-cli and they're working, so we are likely just missing some config here

**Comment by jrjohnson** [comment]
There is some info in the docs about this https://github.com/sglanzer/ember-cli-blanket#reporters-and-testing-mocks You do have to configure mirage to pass the request through and not intercept it.

**Comment by NullVoxPopuli** [comment]
@sglanzer @jrjohnson yeah, though maybe not correctly. From just reading the docs, it looked like I'd just add `this.passthrough('/write-blanket-coverage') to my config.js (where all the mirage routes are)

but no combination of their pass through examples work.

from your docs, I added

```
  this.post(
    '/write-blanket-coverage',
    this.passthrough
  );

  this.pretender.post.call(
  this.pretender,
  '/write-blanket-coverage',
  this.pretender.passthrough
);
```
to my mirage/config.js -- but no dice -- stile don't see the lcov file

the solution to this problem has *got* to be some stupid oversight. bah

**Comment by NullVoxPopuli** [comment]
there is this open issue on ember-cli-mirage: https://github.com/samselikoff/ember-cli-mirage/issues/404

**Comment by NullVoxPopuli** [comment]
I made a discovery.

the output file is output when one test is ran, but not all.

the URL from the browser:
http://localhost:7357/7612/tests/index.html?coverage=true&nojshint

no post to /write-blanket-coverage

but with http://localhost:7357/7612/tests/index.html?coverage=true&nojshint&testId=3e5a63b1

/write-blanket-coverage appears 3 times in the network log.

**Comment by thedrew12** [comment]
I was running into the same issue. I noticed I was getting `TypeError: blanket.instrumentSync is not a function` errors in the console. So ran `ember g ember-cli-blanket` and everything seems to work fine. The passthrough with Mirage is working and I'm getting the coverage generated.

**Comment by NullVoxPopuli** [comment]
when I (re)ran `ember g ember-cli-blanket` the only thing I noticed was that `autostart: true` was commented out in my `blanket-options.js` file.

running `ember test --test-page='tests/index.html?coverage=true&nojshint' `

did not output the lcov file.

adding --server doesn't help either. 

However, I can click `rerun` on any of the tests, the lcov file is generated.

**Comment by NullVoxPopuli** [comment]
as an update, I just ran all my tests individually to see if it was a particular test that was causing the issue, but all individual tests write coverage output. so.. I still don't know what's up

**Comment by NullVoxPopuli** [comment]
I figured it out! If I have acceptance tests, the call to `/write-blanket-coverage` never happens when I run all tests

**Comment by sglanzer** [comment]
Is that potentially related to mirage and missing a `this.passthrough()`?

**Comment by NullVoxPopuli** [comment]
well, I have this in my mirage config.js:

`this.passthrough('/write-blanket-coverage', ['post']);`

which works fine. I have an issue opened on mirage about this: https://github.com/samselikoff/ember-cli-mirage/issues/637#issuecomment-199432488


So, I currently *think* this is a mirage bug -- something to do with acceptance tests blocking the passthrough after all tests finish running.

**Comment by sglanzer** [comment]
Ah, I always use `this.passthrough()`, so it’s possible there is a difference, which kind of sucks ;)

**Comment by NullVoxPopuli** [comment]
Ok, so now I have an ember-cli-blanket problem: https://travis-ci.org/NullVoxPopuli/aeonvera-ui/builds/117598755

```
$ codeclimate-test-reporter < lcov.dat
/home/travis/.nvm/versions/node/v4.3.1/lib/node_modules/codeclimate-test-reporter/formatter.js:33
      throw parseError;
      ^
Unknown input coverage format
```

It appears that `lcov.dat` is empty.

**Comment by sglanzer** [comment]
I haven’t seen that before, but you might want to try running with either Chrome or FireFox as the browser, Phantom can be finicky sometimes and we’ve dropped it entirely for our travis builds (we went with FireFox)

You can look at testem.js and .travis.yml in some of our repos for examples https://github.com/ciena-frost/ember-frost-select/blob/master/.travis.yml#L35 the main changes are to launch xvfb as a display and to switch testem to FireFox

**Comment by NullVoxPopuli** [comment]
oh that's cool that you test it on betas and canaries. I should do that at some point. :-)

**Comment by NullVoxPopuli** [comment]
I HAVE COVERAGE!!!!! https://codeclimate.com/github/NullVoxPopuli/aeonvera-ui/coverage

thanks!!!!!

**Comment by jschilli** [comment]
Glad to hear it. 

If there are any gotchas you encountered either adding a comment here about how you resolved or even better a trouble shooting section in the read me would be appreciated. 



-jeff

**Comment by NullVoxPopuli** [comment]
I pretty much copied your travis setup. Here is mine, for future wanderers:
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/.travis.yml

**Comment by NullVoxPopuli** [comment]
oh! The big thing was also that I was importing Mirage in my acceptance tests. Mirage is already injected in to acceptance tests, so importing it again breaks things.

**Comment by sglanzer** [comment]
Excellent, glad to hear you got it working :)
