### ISSUE TITLE
lcov.dat not generated when using --filter flag

### ISSUE THREAD

**Issue by bierdybard** [sglanzer/ember-cli-blanket#125]
Hello,

Since ember-cli@2.3, running ember test with the --filter flag silently fails to generate lcov.dat.

Running ember test without the --filter flag correctly generates the file. Reverting to ember-cli@~1.13 corrects the issue. 

I have reproduced this on multiple versions of node/npm (0.10, 0.12, 4.4LTS). I'm not sure if this is an ember-cli bug or an ember-cli-blanket bug, but the tests themselves seem to run fine.

Happy to provide whatever other info I can to help with resolving this issue.

This issue persists with the latest version 0.9.1.

**Comment by bierdybard** [comment]
Here is my blanket-options.js:
```
var options = {
  modulePrefix: 'ember_cookiecutter',
  filter: '//.*ember_cookiecutter/.*/',
  antifilter: '//.*(tests|template).*/',
  loaderExclusions: [],
  enableCoverage: true,
  cliOptions: {
    reporters: ['lcov'],
    autostart: true,
    lcovOptions: {
      outputFile: 'lcov.dat'
    }
  }
};
if (typeof exports === 'undefined') {
  blanket.options(options);
} else {
  module.exports = options;
}
```

**Comment by bierdybard** [comment]
This issue was resolved by updating testem.js to use ?coverage=true instead of just ?coverage . I don't know why this is broken now, but this workaround seems to do the trick.

**Comment by sglanzer** [comment]
Thanks for the info @bierdybard, I'll update the README with the explicit version

**Comment by jschilli** [comment]
Thanks for chasing that down.  I suspect that either ember-cli or testem is
building the url differently.  For now documenting that is a reasonable
approach.
