### ISSUE TITLE
Cannot read property error on localhost:4200/tests

### ISSUE THREAD

**Issue by dafortin** [sglanzer/ember-cli-blanket#135]
I did an ember install ember-cli-blanket.

I'm getting the following error on the localhost:4200/tests
<img width="871" alt="screen shot 2016-04-21 at 10 09 15 am" src="https://cloud.githubusercontent.com/assets/18552536/14712047/a7106946-07a9-11e6-8041-68c667de3e79.png">

I'm not getting this error on localhost:4200/tests?coverage

* Note: I did modify the code generated by ember install ember-cli-blanket

**Comment by jschilli** [comment]
@dafortin did you run against #c992c5efb4d154292a5c04233727a7a282f0e318

It's not released so wouldn't expect it to be resolved unless you run against that sha

That was a regression - fixed in #133

not yet release but feel free to verify against that commit.

**Comment by dafortin** [comment]
I will try it :) Thanks !

**Comment by dafortin** [comment]
@jschilli  I'm new to git hub and to ember. Any reference or hint on how I can use a version that was not release yet?

**Comment by jschilli** [comment]
no problem

if you update your package.json to a git url reference e.g. http://stackoverflow.com/a/18049685

e.g.     "broccoli-ember-inline-template-compiler": "git://github.com/jschilli/broccoli-ember-inline-template-compiler.git#use-bower-template-compiler",


but substituting in the correct values.

**Comment by dafortin** [comment]
Regression done. Fixed.
