### ISSUE TITLE
LCOV "SF:" Path Problem

### ISSUE THREAD

**Issue by julianps** [sglanzer/ember-cli-blanket#141]
Hi everybody,

when i create my coverage report (using the lcov-reporter), sonarqube is not able to make the analysis.  **I'm working on an ember-addon project.** The directory Structure is as follows: (example file concat.js)

-- $projectname$
.. |
.. |-- app
.... |
.... |-- helpers
........|
........| - concat.js

The LCOV output is:

SF:$projectname$/helpers/concat.js
DA:1,1
DA:2,1
... 
LF:9
LH:9
end_of_record

Well, of course SonarRunner does not find the file on the path reported in the LCOV File.

The solution would be, that the LCOV output is:

SF:$projectname$/app/helpers/concat.js

Is there a solution for this issue i didn't found or is the ember-cli-blanket project not suitable for addons in general?

**Comment by sglanzer** [comment]
We use blanket for our addon projects - some tools do require modifications to the LCOV output however.  You can see an example where we use `sed` to do manipulation of the LCOV output after the coverage has been generated here https://github.com/ciena-frost/ember-frost-core/blob/master/.travis.yml#L23

**Comment by julianps** [comment]
that solved my problem thanx. There is one problem left. It seems that the coverage-analysis is not processed on the original source files, so there is a difference in the files that sonar scans and the coverage reports. But My Coverage is now successfully inserted in sonar. Thnx
