### ISSUE TITLE
[ember-cli-blanket]:error: TypeError: Cannot read property 'type' of undefined while writing blanket coverage

### ISSUE THREAD

**Issue by chauhansudhir** [sglanzer/ember-cli-blanket#142]
All of a sudden I started getting the following error.
[ember-cli-blanket]:error: TypeError: Cannot read property 'type' of undefined while writing blanket coverage

please suggest if anyone already know the fix.

**Comment by andrewmtoy** [comment]
I fixed this issue by upgrading pretender to 1.1.

**Comment by jschilli** [comment]
thanks @andrewmtoy should be resolved (via doc ) with #158
