### ISSUE TITLE
Add loader.js to dependencies?

### ISSUE THREAD

**Issue by oniofchaos** [sglanzer/ember-cli-blanket#144]
I otherwise don't need `loader.js` in my apps, but to use `ember-cli-blanket` I also have to add this dependency. Would it be desirable to add `loader.js` to the dependencies here so that I wouldn't have to do this?

**Comment by jschilli** [comment]
AFAIK loader.js is required by ember-cli and recently shifted from being a bower dependency to an npm dependency.

So I can't imagine it not being a requirement for some time
