### ISSUE TITLE
Need to make work with test-loader.js in npm

### ISSUE THREAD

**Issue by rwwagner90** [sglanzer/ember-cli-blanket#145]
Ember-CLI 2.7.0-beta.1 moved test-loader.js out of bower and into npm and now I get errors that it can't find it.

I mistakenly posted an issue about it on Ember-CLI and just found out it was an ember-cli-blanket issue.

https://github.com/ember-cli/ember-cli/issues/5974

**Comment by offirgolan** [comment]
ping @sglanzer 😺

**Comment by sglanzer** [comment]
Yeah, sorry guys - this is something that I obviously need to fix - will get this done today

**Comment by rwwagner90** [comment]
Woo thanks @sglanzer! I was hoping ember-cli-code-coverage would be useable soon, but looks like we'll have to keep using this for the foreseeable future, so a patch would be awesome 😄

**Comment by sglanzer** [comment]
That was my line of thinking as well (re: ember-cli-code-coverage) and we're putting some effort into that, but you're right that we need this as a stopgap

**Comment by sglanzer** [comment]
@EWhite613 is going to take a stab at this, I'll throw in some help when I free up later today

**Comment by sglanzer** [comment]
@EWhite613 put in a fix #152 and we've published 0.9.6 - let us know if that takes care of the problem on your end and we'll close this

**Comment by rwwagner90** [comment]
@sglanzer @EWhite613 it seems that the blueprint no longer adds the necessary lines to tests/index.html. That will need to be updated to work with the new format as well.

**Comment by offirgolan** [comment]
@sglanzer seems like 0.9.6 fixed the issue. Thanks for the quick response!

**Comment by rwwagner90** [comment]
Should just need to add `{{rootURL}}` to the path it is looking for to add lines after.

**Comment by rwwagner90** [comment]
@offirgolan it does not add the necessary lines to index.html for you though does it?

**Comment by sglanzer** [comment]
@rwwagner90 he's probably using it against a project that had run the blueprint previously

**Comment by offirgolan** [comment]
> he's probably using it against a project that had run the blueprint previously

Yup. I ran the generator and can confirm it doesnt add the scripts to the tests/index.html

**Comment by rwwagner90** [comment]
Yeah, probably. Do you want me to submit a PR for looking for the `{{rootURL}}` stuff @sglanzer or can one of you guys do it real quick? Just need to add it when looking for lines to add after, and also add it to each line, so you end up with stuff like:

```html
<script src="{{rootURL}}assets/blanket-options.js"></script>
<script src="{{rootURL}}assets/blanket-loader.js"></script>
```

**Comment by sglanzer** [comment]
@rwwagner90: @EWhite613 is going to do a quick PR - definitely appreciate you testing/catching that one

**Comment by offirgolan** [comment]
@sglanzer I got you fam

**Comment by sglanzer** [comment]
Thanks @offirgolan - 0.9.7 published

**Comment by rwwagner90** [comment]
Everything works great. Thanks everyone! 🎉
