### ISSUE TITLE
DEPRECATION: Overriding init without calling this._super is deprecated.

### ISSUE THREAD

**Issue by rafael-paiva** [sglanzer/ember-cli-blanket#148]
After upgrading to `ember-cli 2.6.2` I get the following deprecation warning when starting my app:

`DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `Ember CLI Blanket`
    at Function.Addon.lookup (/Users/v-paivar-ave/Code/ember-update/awp-ptc/node_modules/ember-cli/lib/models/addon.js:896:27)`

This seems to be already fixed on master but not on version `0.9.4`

**Comment by sglanzer** [comment]
Fixed a while ago - we're now on 0.9.8, just haven't been keeping the issues clean
