### ISSUE TITLE
No ouput files generated

### ISSUE THREAD

**Issue by rwwagner90** [sglanzer/ember-cli-blanket#157]
I am having an issue where I see all the coverage reports in my browser just fine, when I run `ember test --server`, but no output files are generated. My blanket options look like this:

```js
/* globals blanket, module */

const options = {
  modulePrefix: 'sa',
  filter: '//.*sa/.*/',
  antifilter: '//.*(tests|template|config|mirage|instance-initializers|components/liquid-|components/lf-|components/lm-|transitions|liquid-fire).*/',
  loaderExclusions: [],
  enableCoverage: true,
  cliOptions: {
    reporters: ['lcov'],
    autostart: true,
    lcovOptions: {
      outputFile: 'lcov.dat'
    }
  }
};
if (typeof exports === 'undefined') {
  blanket.options(options);
} else {
  module.exports = options;
}

```

I would expect an `lcov.dat` file to show up, but it does not. We are using mirage, but I think we have the passthrough wired up correctly. Is this what would happen with mirage if we didn't configure it right? We would see coverage in the browser, but get no output files?

Not really sure where to begin debugging this.

**Comment by jschilli** [comment]
The easiest way to debug this is in chrome. Open the inspector. At the
conclusion of the test run you should see the post to
`write-coverage-data`. If you do not see it, then something is eating your
post request.

Also check the console for any warnings or errors at the end of the run.

**Comment by rwwagner90** [comment]
@jschilli is it supposed to be `write-coverage-data` or `write-blanket-coverage`?

**Comment by jschilli** [comment]
Was typing from memory

**Comment by rwwagner90** [comment]
@jschilli I am seeing this error in my terminal:

```
'[ember-cli-blanket]:error: TypeError: Cannot read property \'type\' of undefined while writing blanket coverage'
```

**Comment by jschilli** [comment]
In your terminal and not in the Browser console?  Did you see the POST call in the browser?

**Comment by rwwagner90** [comment]
@jschilli there is no POST in the browser. The other error in the terminal may have been related to a `debugger` I had in trying to figure stuff out.

**Comment by jschilli** [comment]
No post suggests that mirage or pretender or other xhr hook is eating the
request.

My recollection is that there is a message in the browser console before we
attempt to POST.

Not at a computer to verify - but I would check in on the mirage config

**Comment by rwwagner90** [comment]
@jschilli it appears we just needed to update mirage and pretender. Probably need to add version requirements to the config

**Comment by sglanzer** [comment]
@rwwagner90 what versions are you using?  We've been on mirage 0.1.x for a while, but I believe there are some people in the company running 0.2.x as well

**Comment by rwwagner90** [comment]
@sglanzer I believe we were previously on 0.1.11 and updating to 0.1.13 worked. The versions listed in the docs for ember-cli-code-coverage seem to be required over here too. Would you like me to copy their version requirements and submit a PR for the README here?

**Comment by sglanzer** [comment]
@rwwagner90 That would be great :)
