### ISSUE TITLE
Code coverage breaks 'no jshint' for tests

### ISSUE THREAD

**Issue by djmitchella** [sglanzer/ember-cli-blanket#16]
Another one related to the way things are loaded differently, I think. Repro steps:
1. ember init
2. ember serve
3. go to localhost:4200/tests; there's jshint tests there (and nothing else)
4. check the 'disable jshint' box. Now all the tests disappear.
5. Stop server, npm install ember-cli-blanket --save-dev, ember generate ember-cli-blanket
6. ember serve
7. go to localhost:4200/tests. Tests still pass, but:
8. check the 'disable jshint' box. Now, nothing changes; with blanket there, all the jshint tests still run.

(I'm not sure, but from looking at test-loader.js in ember-cli-test-loader, it seems that jshint is somehow automatically getting run on everything that's loaded. I'm guessing that the nojshint setting stops test-loader loading the files, but blanket is still loading them anyway for coverage purposes; I'm not sure if it's possible to fix this without changing how the nojshint code works)

**Comment by sglanzer** [comment]
Some investigation into using the client flags would be useful.  Ideally I'd only like to instrument and run the coverage when the "enable coverage" checkbox is flagged, so the nojshint would fall into a similar investigation.

**Comment by djmitchella** [comment]
A quick and dirty way to solve this is to change the end of blanket-loader.js from:

    if (!exclude) {

to

    if (!exclude && !QUnit.urlParams.nojshint) {

 That means that disabling jshint also (effectively) turns off code coverage, but I can live with that for now.

**Comment by sglanzer** [comment]
@djmitchella Good to know - definitely a useful starting point for making better use of the flags.

**Comment by djmitchella** [comment]
This is fixed in 0.5.0.
