### ISSUE TITLE
how to set other options such as `branchTracking` flag?

### ISSUE THREAD

**Issue by huafu** [sglanzer/ember-cli-blanket#31]
First of all, thanks for this great addon!

Looking at [blanket options](https://github.com/alex-seville/blanket/blob/master/docs/browser_options.md) how can I set them thru the config? Like setting the `flags` to `branchTracking`  for example?

**Comment by jschilli** [comment]
you should be able to set them directly in blanket-options.js

**Comment by huafu** [comment]
Thanks, but I tried and the only options there are not even named as the one described in blanket help, so I do not think this is the way :-/

**Comment by jschilli** [comment]
I set debug=true and that worked. 

When I get back to my computer I'll take a look

**Comment by huafu** [comment]
well, maybe just my flag is not working then haha. Thanks for looking tho

**Comment by jschilli** [comment]
@huafu - confirmed that below works.

Please confirm and close.  
```
blanket.options({ 
   modulePrefix: 'ngam',
   filter: '//.*ngam/.*/',
   antifilter: '//.*(tests|templates).*/',
   loaderExclusions: [],
   ignoreScriptError: true,
   branchTracking: true,
   enableCoverage:false
});
```

**Comment by huafu** [comment]
I'll test that as soon as I can and close if it's working. Thanks again!

**Comment by jschilli** [comment]
I've been running for a few days with this option enabled as described.  closing

**Comment by huafu** [comment]
Ok thanks. I still did not get the time to test that sorry. It's in my config but I had other projects to work on and a huge bug in the compile process of my project so get DS not get the chance to test that.
