### ISSUE TITLE
Add test suite to the project

### ISSUE THREAD

**Issue by jschilli** [sglanzer/ember-cli-blanket#39]
We need a standard test suite, particularly as we add new capabilities.

@sglanzer I prefer mocha and have some boilerplate that makes it easier to test addons - any strong preference for mocha vs qunit?

**Comment by sglanzer** [comment]
Definitely fine with mocha - I prefer the language, but stuck with qunit in my last project (ember-cli-mocha wasn't available at the time).  More than happy to see some examples/try it out in this project.

**Comment by jschilli** [comment]
cool - I’ll also publish a test project with the lcov-writing branch so folks can check it out - I’m wrapped on other stuff for a day or two but will get back to it

**Comment by sglanzer** [comment]
Fantastic, thanks!

**Comment by jschilli** [comment]
closed by #38
