### ISSUE TITLE
ember-cli-qunit 0.3.11 autostart handling

### ISSUE THREAD

**Issue by avdv** [sglanzer/ember-cli-blanket#41]
Hi.

Two days ago ember-cli-qunit was released, and because of this change https://github.com/ember-cli/ember-cli-qunit/commit/98c8d370d574adc4deb2ab438edd0d248b22155b no tests are run anymore.

Giving the `autostart=true` config as a URL parameter did not work either.

Any idea how to resolve this in ember-cli-blanket or is that an issue for ember-cli-qunit or even blanket.js?

Thanks

**Comment by sglanzer** [comment]
If you look at the top lines of lib/start.js you can see that the
ember-cli-qunit behavior has flip flopped a few times on this.  Since we
set auto start to false to allow instrumentation to finish, qunit.start
must be called explicitly.  As a temporary measure you can uncomment the
qunit.start in start.js and we'll look into a better way to detect this
behavior so that any further flip flops don't have this impact.

**Comment by hjdivad** [comment]
@sglanzer any reason why blanket can't do the same thing as ember-cli in https://github.com/ember-cli/ember-cli-qunit/commit/98c8d370d574adc4deb2ab438edd0d248b22155b and so let the user have the final say on whether tests should automatically start?

**Comment by sglanzer** [comment]
Looks reasonable to me, the only requirement is that autostart must be false while the instrumentation is occurring.

If you want to submit a pull request I'll merge it, otherwise we'll try to get to this sometime today.

**Comment by hjdivad** [comment]
@sglanzer cool.  It sounds like you don't need any changes from ember-cli-qunit, but let me know if you do

**Comment by sglanzer** [comment]
@hjdivad just a note since it's going to work in this case, but ember-cli-qunit is actually overriding the value of autostart downstream.  Ember-cli-blanket is upstream, so it won't hurt in this case, but it may be something you want to fix.

```
var autostart = QUnit.config.autostart !== false;
QUnit.config.autostart = false; // Overrides the value

   setTimeout(function() {
     TestLoader.load();
     // Doesn't set the value back, everything downstream will get 'false'
     if (autostart) {
      QUnit.start();
    }
   }, 250);

**Comment by hjdivad** [comment]
@sglanzer that's a great point.  Unfortunately ember-cli-qunit has the same problem ember-cli-blanket has: we need QUnit to not *actually* autostart (in ember-cli-qunit's case to work around a tedious chrome deficiency when using sourcemaps).

I don't see a way for us to not interfere downstream except by requiring users to use a different flag from the standard `QUnit.config.autostart`.  Do you?

**Comment by sglanzer** [comment]
@hjdivad Can we just set the value back into the property after consuming it?  I.e. Instead of calling Qunit.start() in the addon, just set qunit.config.autostart back to the value of 'autostart' and let it fall through?

**Comment by hjdivad** [comment]
@sglanzer at that point it's too late I think.  QUnit will check `autostart` during dom ready, but if we start that early we'll run into the issue with chrome not having loaded sourcemaped files yet.

The problem will, presumably, go away on its own once chrome fixes their bug and we don't need this 250ms delay.

**Comment by hjdivad** [comment]
@sglanzer we could add something to QUnit's api to have more control over when `autostart` actually starts but I doubt they'd want to complicate their API for something expected to be temporary.

**Comment by hjdivad** [comment]
@sglanzer sorry I read your comment as if you were talking about ember-cli-qunit.  What are the actual runtime requirements of ember-cli-blanket?  Do you just need the tests to start after a short delay?  If so you probably don't need to do anything at all for newer versions of ember-cli-qunit.

**Comment by sglanzer** [comment]
@hjdivad No, I was referring the ember-cli-qunit, but obviously if it's a workaround then we can't/shouldn't do anything about it.  Blanket needs to instrument all of the files in the application, not just the test files, which is why we make use of the autostart false as well.

**Comment by sglanzer** [comment]
Unfortunately I'm bogged down with a product demo and won't be able to address this until the weekend.  If anyone else wants to have a go before then, feel free

**Comment by sglanzer** [comment]
I've added a fix for this available in 0.5.1 - check it out and if it addresses your issue we can close this.

**Comment by hjdivad** [comment]
cc @avdv 

I'm guessing you guys don't need anything more from `ember-cli-qunit` but if you do, please ping me.  Thanks ^_^

**Comment by sglanzer** [comment]
Thanks for your help @hjdivad, always nice to chat with other people working on ember-cli projects =)

**Comment by avdv** [comment]
Thanks guys, it works as desired. Closing.
