### ISSUE TITLE
Running Tests causes 'ReferenceError: Can't find variable: moduleLoaderFinish'

### ISSUE THREAD

**Issue by chrisvdp** [sglanzer/ember-cli-blanket#42]
I installed by running `ember install:addon ember-cli-blanket`. 

I am running ember-cli v0.2.1 with ember-cli-mocha v0.5.0. When I start the tests I get the error 
`✘ ReferenceError: Can't find variable: moduleLoaderFinish (http://localhost:7357/assets/test-lo
ader.js:105)`

The error is being thrown from `assets/start.js:56` which is the following snippet

```
runner.on('end', function() {
    // annotate all files that match but were never referenced
   moduleLoaderFinish();
   blanket.onTestsDone();
});
```

**Comment by jschilli** [comment]
@chrisvdp is blanket-loader.js included in your tests/index.html?

**Comment by chrisvdp** [comment]
it isn't

**Comment by jschilli** [comment]
add `<script src="assets/blanket-loader.js"></script>` to tests/index.html - it should be automatic when installing.

we have a new version forthcoming that changes the way this is maintained.

let me know.

**Comment by chrisvdp** [comment]
looks like we had the existing script tags as absolute links not relative so the script wasn't finding them and inserting the tags.
