### ISSUE TITLE
missing lcov.txt in root dir after ember test

### ISSUE THREAD

**Issue by jrowlingson** [sglanzer/ember-cli-blanket#44]
With the following config:

```
  cliOptions: {
    lcovOptions: {
      outputFile: 'lcov.txt'
    },
    reporters: ['lcov']
  }
```

I am not seeing the lcov file in the root dir after running ```ember test```. Is there something I am missing?

**Comment by sglanzer** [comment]
I believe it's being output as "coverage.json" currently, which is the default.  We'll have to look into why the options aren't being respected.

**Comment by jschilli** [comment]
Are you running with ?coverage 

In the testem.json

We need to either update the doc or figure out how to specify an alt testem config so it's on by default

-jeff

**Comment by jschilli** [comment]
Ouch. I can look at that this weekend 

-jeff

**Comment by jschilli** [comment]
my testem.ci.json file looks like:
```
{
  "framework": "qunit",
  "test_page": "tests/index.html?coverage",
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "Chrome"
  ]
}
```

ember test --config-file testem.ci.json

the `?coverage` is what turns on coverage testing

another way to verify is to run ember test watch - append the coverage query parm or select the coverage checkbox (if qunit) 

run your tests and the file should be there.

I'll update the docs in a PR soon

**Comment by jrowlingson** [comment]
I was missing the ```?coverage``` part. I am now seeing the lcov.txt appear in the root dir. Thanks for your help here.
