### ISSUE TITLE
PUT & POST requests with content type application/json are stalling in ember-cli http-proxy

### ISSUE THREAD

**Issue by JohnQuaresma** [sglanzer/ember-cli-blanket#53]
Hello ember-cli-blanket team,

First of all, this add-on is great.  So glad to have coverage built into my ember-cli testing process!

Now for my issue - after upgrading to the latest version (0.5.1), which contained a fix for x-www-form-urlencoded POST requests hanging in the ember-cli http-proxy, I started having similar issues with POST and PUT requests of content-type application/json.

I've verified that when I downgrade to 0.4.0, everything works fine.  Can someone please take a look?  I'd love to take advantage of your latest fixes, but I have to stay on the older version for now as this issue is blocking me.

Thanks so much!

**Comment by jschilli** [comment]
@JohnQuaresma can you share some config or description there of so I can replicate for testing changes?  I don't have http-proxy setup.

0.4.0 didn't write coverage data so none of the middleware functionality was there.

should be easily fixable if I can get an environment setup to recreate it

**Comment by cah-briangantzler** [comment]
Having the same on [issue 46](https://github.com/sglanzer/ember-cli-blanket/issues/46) which I though we had fixed. I dont know of any public api that would accept a post or put, so cant do a jsbin. To reproduce create an application that posts to localhost:4200\yourservice and start ember with "ember server --proxy=actualserviceurl". You should see the post hang.

**Comment by jschilli** [comment]
@JohnQuaresma @cah-briangantzler can one or both of you share the console output of ember serve when you observe this?  I setup this morning to proxy our app using `ember serve --proxy` and PUT, POST, GET all work just fine (normally proxy through nginx so I hadn't seen any issues)

I'm setup here to help fix this just need some additional detail on this.

```
POST /mobilews/logonUser?ws1411 200 1303.169 ms - 1334
GET /mobilews/uuxConfiguration 200 228.681 ms - 125
GET /mobilews/userProfile 200 278.158 ms - 302
```

**Comment by cah-briangantzler** [comment]
Proxying to http://localhost:8080/
Livereload server on port 35729
Serving on http://localhost:4200/latest/cabinet/

The network request in the browser sits at pending for a while, then cancels. I then get this in the log

Error proxying to http://localhost:8080/
socket hang up
Error: socket hang up
    at createHangUpError (http.js:1477:15)
    at Socket.socketOnEnd [as onend] (http.js:1573:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

It does not echo the actual request though when there is an error.

**Comment by jschilli** [comment]
hmmm, 

are you using generated mocks or proxies?

One other way to skin the cat here is to add an option to disable server middleware when running in 'ember serve' mode vs ember test - I added it to both b/c I generally leave ember serve running and toggle between tests and app

the original use case for writing coverage output files was for ci test support.

would be easy to add `disableServerMiddleware:true` to options

**Comment by JohnQuaresma** [comment]
@jschilli did you try it with content-type application/json?  Content type x-www-form-urlencoded works fine - it's json that hangs.  I was using the http-proxy (not mocks / fixtures).

Another thing I noticed is that your middleware is executing even when not running unit / acceptance tests, which I found to be quite odd.  I didn't think that was possible, but as soon as I removed ember-cli-blanket and/or downgraded, the problem went away.

**Comment by jschilli** [comment]
@JohnQuaresma I did - 

Here's the output when I run with the following flags:

`DEBUG="express:*, body-parser:*, ember-cli:serve, morgan" ember serve --proxy`

```
express:router dispatching POST /endpoint/logonUser?ws1373 +83ms
  express:router query  : /endpoint/logonUser?ws1373 +0ms
  express:router expressInit  : /endpoint/logonUser?ws1373 +1ms
  express:router jsonParser  : /endpoint/logonUser?ws1373 +0ms
  body-parser:json content-type "application/json; charset=UTF-8" +0ms
  body-parser:json content-encoding "identity" +1ms
  body-parser:json read body +0ms
  body-parser:json parse body +0ms
  body-parser:json parse json +0ms
  express:router urlencodedParser  : /endpoint/logonUser?ws1373 +0ms
  body-parser:urlencoded body already parsed +1ms
  express:router <anonymous>  : /endpoint/logonUser?ws1373 +0ms
  express:router <anonymous>  : /endpoint/logonUser?ws1373 +0ms
  express:router <anonymous>  : /endpoint/logonUser?ws1373 +1ms
  express:router jsonParser  : /endpoint/logonUser?ws1373 +0ms
  body-parser:json body already parsed +0ms
  express:router <anonymous>  : /endpoint/logonUser?ws1373 +0ms
  express:router logErrors  : /endpoint/logonUser?ws1373 +0ms
  express:router logger  : /endpoint/logonUser?ws1373 +0ms
  express:router <anonymous>  : /endpoint/logonUser?ws1373 +0ms
```

can you run yours with the `DEBUG=` flags above - might shed some clues

WRT the middleware running.  as I said above I added it to `serverMiddleware` to support the usecase of coverage reporting when running in ember serve mode - there is (currently) nothing to indicate that it is or isn't in testing mode.

Simplest thing for now is to either a) remove it from serverMiddleware or b) add a flag to disable it (as I suggested above)

**Comment by cah-briangantzler** [comment]
I also am not using mocks at the moment due to a bug (all my models have custom adapters and due to dasherized, only during tests, ember data fails to lookup the correct adapter) but do plan on using mocks as soon as the bug is corrected.

I would also vote for the middleware only active during test. We typically are running another server in test mode in another window to switch back and forth as you are suggesting.

My original problem was the all posts were failing. With the fix my login is working but @JohnQuaresma is right, that is x-www-form-urlencoded. Its my JSON ones now that hang.

**Comment by cah-briangantzler** [comment]
I also hate to be such a newbie but could you point me to a page to read more what the following does? I tried it and would like to know more about what is happening 

DEBUG="express:*, body-parser:*, ember-cli:serve, morgan" ember serve --proxy

**Comment by jschilli** [comment]
@cah-briangantzler  see https://www.npmjs.com/package/debug

**Comment by JohnQuaresma** [comment]
I ran with those flags, but I get absolutely no debug output from express or body parser - only morgan:

  morgan log request +1m
PUT /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 500 60095.294 ms - -
  morgan log request +2ms
PUT /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be 500 60101.915 ms - -

**Comment by jschilli** [comment]
what version of ember-cli? (I’m on 0.2.3)

I’m working on a fix to make serverMiddleware opt in only.

not sure how to debug the issue without some clues to recreate.

**Comment by JohnQuaresma** [comment]
I'm on 0.2.3 as well.

I was able to get some more debug output - I think the syntax you had wasn't working for me.  I just used DEBUG=*.  Here's the debug output from the requests:

  express:router dispatching PUT /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +10s
  express:router query  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +1ms
  express:router expressInit  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router <anonymous>  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router <anonymous>  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router <anonymous>  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +2ms
  ember-cli:serve-files serving: /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  ember-cli:serve-files serving: (prefix stripped) /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router jsonParser  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +1ms
  body-parser:json content-type "application/json; charset=UTF-8" +10s
  body-parser:json content-encoding "identity" +1ms
  body-parser:json read body +0ms
  body-parser:json parse body +12ms
  body-parser:json parse json +0ms
  express:router <anonymous>  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +13ms
  express:router logErrors  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router logger  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router <anonymous>  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +1ms
  express:router dispatching PUT /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +1ms
  express:router query  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router expressInit  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router <anonymous>  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router <anonymous>  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router <anonymous>  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +1ms
  ember-cli:serve-files serving: /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  ember-cli:serve-files serving: (prefix stripped) /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router jsonParser  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  body-parser:json content-type "application/json; charset=UTF-8" +3ms
  body-parser:json content-encoding "identity" +1ms
  body-parser:json read body +0ms
  body-parser:json parse body +0ms
  body-parser:json parse json +0ms
  express:router <anonymous>  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +1ms
  express:router logErrors  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router logger  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router <anonymous>  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  morgan log request +1m
PUT /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be 500 60024.019 ms - -
  morgan log request +1ms
PUT /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 500 60021.317 ms - -

**Comment by JohnQuaresma** [comment]
For what it's worth, the express & body parser messages came straight away - as soon as I sent the request.  However, the morgan logs didn't show up until a full minute (server timeout?) after the body-parser / express messages.  

Here is the output from that same debugging when I downgrade to ember-cli-blanket 0.4.0 (please note that body-parser does not get called, the morgan output is printed straight away, and the request is successful):

express:router dispatching PUT /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +6s
  express:router query  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router expressInit  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router <anonymous>  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +1ms
  express:router <anonymous>  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router <anonymous>  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +1ms
  ember-cli:serve-files serving: /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  ember-cli:serve-files serving: (prefix stripped) /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router logger  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router <anonymous>  : /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be +0ms
  express:router dispatching PUT /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +1ms
  express:router query  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router expressInit  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router <anonymous>  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router <anonymous>  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router <anonymous>  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +1ms
  ember-cli:serve-files serving: /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  ember-cli:serve-files serving: (prefix stripped) /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router logger  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +0ms
  express:router <anonymous>  : /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 +1ms
  morgan log request +34ms
PUT /api/aspect/037c8c49-84cb-4106-b587-a29c04e346be 200 37.175 ms - -
  morgan log request +351ms
PUT /api/entity/8d1eafa9-8a64-4c2c-8705-fe368b1a7075 200 385.300 ms - -

**Comment by jschilli** [comment]
thanks @JohnQuaresma - I'll post a note here when the PR is up to disable serverMiddleware

**Comment by jschilli** [comment]
@JohnQuaresma @cah-briangantzler can you try this branch before I PR?

npm install "git://github.com/jschilli/ember-cli-blanket/#fix-middleware"

this completely removes `serverMiddleware` - I'll need to take another pass when I have time to figure out how to selectively enable it

**Comment by JohnQuaresma** [comment]
I can't right now - I'm in the middle of something else.  @cah-briangantzler?  I may be able to get to this later today.

**Comment by jschilli** [comment]
np, let me know

**Comment by cah-briangantzler** [comment]
I tried that branch. My JSON post now works
```
GET /services/clinical/medicationorders?sort(clinicalOrderDate)=true&fieldsIgnore=medicationOrderLines&locationId=1&clinicalOrderDate=%40between(1430884800000%2C1430971199999) 200 18.659 ms - 2
POST /services/inventory/adjustments 200 51.113 ms - 570
GET /services/inventory/inventory/db775b15-47a6-4073-8242-757cd1f4035a 200 13.357 ms - 319
```

The main reason we wanted to upgrade was for the reports. So running in test mode the reports were created and uploaded successfully

```
11:19:41.925 INFO  - ANALYSIS SUCCESSFUL, you can browse http://localhost:9000/dashboard/index/vitalpath-ember-cli
```

I think it looks good for me

**Comment by cah-briangantzler** [comment]
Can a tag be created for this? Currently my code is referencing the master branch and would like to not be doing that

**Comment by jschilli** [comment]
@cah-briangantzler I would recommend cloning into your own repo and use a tag there.

@sglanzer manages the release/push to npm
