### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sir-dunxalot** [sglanzer/ember-cli-blanket#58]
I installed with `ember install ember-cli-blanket` and ran into two issues:

1. The readme still has the deprecated `ember install:addon ember-cli-blanket` syntax
2. Running `ember install ember-cli-blanket` throws an error:

```shell
version: 0.2.3 # Ember CLI version
Installed packages for tooling via npm.
installing
  create tests/blanket-options.js
Installing browser packages via Bower...
  not-cached git://github.com/alex-seville/blanket.git#~1.1.5
  resolved git://github.com/alex-seville/blanket.git#1.1.5
Installed browser packages via Bower.
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`. #error
```

**Comment by mitchlloyd** [comment]
Let it be known that the second issue is probably this bug in ember-cli: 

https://github.com/ember-cli/ember-cli/pull/3846

**Comment by givanse** [comment]
`0.2.5` was released mainly because of this bug

**Comment by sir-dunxalot** [comment]
Ok, great. I'll close this.
