### ISSUE TITLE
Add mocha support.

### ISSUE THREAD

**Issue by chrisvdp** [sglanzer/ember-cli-blanket#59]
I noticed that qunit is hardcoded.

**Comment by jschilli** [comment]
ember-cli-blankets supports both mocha and qunit - what are you referring to?

**Comment by chrisvdp** [comment]
https://github.com/sglanzer/ember-cli-blanket/blob/master/index.js#L30

**Comment by chrisvdp** [comment]
Seems to cause 
```
cploeg-mac:webui cploeg$ ember test
version: 0.2.3
BuildingWarning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT, no such file or directory '/Users/cploeg/Web/coverity-service/webui/tmp/tree_merger-tmp_dest_dir-Afx6Fun8.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'
Built project successfully. Stored in "/Users/cploeg/Web/coverity-service/webui/tmp/class-tests_dist-yM5kvrgh.tmp".
not ok 1 PhantomJS - Browser "/usr/local/bin/phantomjs --remote-debugger-port=5000 --remote-debugger-autorun=true /Users/cploeg/Web/coverity-service/webui/node_modules/ember-cli/node_modules/testem/assets/phantom.js http://localhost:7357/943" exited unexpectedly.

1..1
# tests 1
# pass  0
# fail  1
```

**Comment by jschilli** [comment]
hmm, not sure how to get to qunit is hardcoded from that message.

sound more likely that blanket.js is not installed 

does bower_components/blanket exist?

if not, could be tied to install issue

bower install —save-dev blanket

**Comment by chrisvdp** [comment]
It does exist. When I changed https://github.com/sglanzer/ember-cli-blanket/blob/master/index.js#L30 to reference `dist/mocha/blanket-mocha.js` in the HEAD version of blanket (it hasn't been included in a release, but it looks like they haven't had a release in almost a year) the message goes away.

**Comment by jschilli** [comment]
YMMV - I don’t even see that file in the standard blanket distro.

I use mocha and blanket all day 

what version of blanket is installed?  I have 1.1.5

**Comment by chrisvdp** [comment]
I can use blanket and mocha in the browser, the issue is trying to get reporter output in ci.

**Comment by jschilli** [comment]
@chrisvdp I've just reconfirmed that ember-cli-blanket works with ember-mocha with the released version of blanket.

I'm happy to help with that config - given how ember-cli-blanket is tied into blanket and ember-mocha I don't have any interest in adding a 3rd config 

closing for now
