### ISSUE TITLE
Logging Error object [object Object] when running with --server

### ISSUE THREAD

**Issue by vitapluvia** [sglanzer/ember-cli-blanket#71]
Looks like the runner is logging out and error object from the vendor file when I run my tests.  Not sure if this is happening for others, but it's occurring here: 
https://github.com/sglanzer/ember-cli-blanket/blob/master/vendor/blanket-require.js#L96

It needs to be changed from console.log(err) to console.log(err.stack) or something similar.
Not sure if this is ember-cli-blanket or the vendor lib, but thought I should mention this issue regardless.

**Comment by jschilli** [comment]
@vitapluvia still an issue with 0.9.1?  the code has changed a bunch since then and your file ref above doesn't give me a clue.

Please reopen if still an issue
