### ISSUE TITLE
require.unsee is not exposed in custom require function

### ISSUE THREAD

**Issue by notmessenger** [sglanzer/ember-cli-blanket#85]
Causes the error of "unable to require.unsee, please upgrade loader.js to >= v3.3.0" to be thrown in the console.  See https://github.com/ember-cli/ember-cli-test-loader/issues/15#issuecomment-141466093

**Comment by elwayman02** [comment]
@sglanzer any thoughts on this?

**Comment by jschilli** [comment]
@elwayman02 have you tried require.unsee = savedRequire.unsee - I suppose we should look at a cleaner proxy on require.

I'm slammed and don't have near term bandwidth to look @ it but PRs or pointers welcome

**Comment by elwayman02** [comment]
Yea I don't have time to look at it this week at the very least...just heard about it from someone else and it affects stuff I'm working on so I wanted to see if there was any traction here.

**Comment by sglanzer** [comment]
We could definitely do some work on a cleaner require proxy - I'm going to do some work on this project again over the next few weeks.

I can dig around the links for steps to reproduce, but if anyone has time to document steps it would be a big help.

**Comment by notmessenger** [comment]
You can run the EmberCli-1.13.8 branch of https://github.com/softlayer/sl-ember-components to replicate the error.

**Comment by sglanzer** [comment]
I haven't seen this in any of my addons, but I'll find some time to look
into this after finishing the addon exclusions work.

**Comment by pixelhandler** [comment]
I'm seeing this error in my addon also test coverage report drastically changed from 93% to 16% seems inaccurate. I did upgrade from ember-cli 1.13.8 to 1.13.13. that's when I noticed this `unable to require.unsee, please upgrade loader.js to >= v3.3.0` when running `ember t -s`

**Comment by avdv** [comment]
> I did upgrade from ember-cli 1.13.8 to 1.13.13

That's exactly what I was doing, too. Same problem here.

> have you tried require.unsee = savedRequire.unsee

That seems to work, thanks @jschilli.

**Comment by jagthedrummer** [comment]
I just ran into this issue. Is there any ETA on a fix?

In the mean time where should I add `require.unsee = savedRequire.unsee`?

**Comment by jschilli** [comment]
@jagthedrummer adding that won't change the 1.13.13 issue with accuracy of reporting.

There is a series of changes that change up the way we instrument code that is good with 1.13.13 forward but we're waiting on an upstream dep PR on blanket.js - no action on that yet so we'll need to make a decision about creating a temporary fork.

cc: @sglanzer

**Comment by jagthedrummer** [comment]
Ah! Thanks for the info @jschilli. I'm actually on ember-cli 2.2.0-beta.6 and I'm seeing the same error reported above, but I'm also getting no coverage info at all. (Not sure if that's new/useful info...)

**Comment by jschilli** [comment]
Can you retest this with version 0.9.1 (and be sure to update blanket.js via `ember g ember-cli-blanket`) and reopen if it still persists

**Comment by TaylorHG** [comment]
Been lurking this for a while now

@jschilli your 0.9.1 update solved the issue for me. Thanks a million, you're a rockstar.
