### ISSUE TITLE
Could not find module `ember-sinon/acceptance-tests/sinon` imported from `exam-sim-ember/acceptance-tests/sinon

### ISSUE THREAD

**Issue by lolmaus** [sglanzer/ember-cli-blanket#87]
Got both ember-cli-blanket and ember-sinon in my project.

Blanket complains in browser console during tests:

> Error: Could not find module `ember-sinon/acceptance-tests/sinon` imported from `exam-sim-ember/acceptance-tests/sinon`

Steps to reproduce:

```
ember new blah
cd blah
ember install ember-cli-blanket
ember install ember-sinon
ember s
```

Then go to http://localhost:4200/tests/ , enable coverage and look into the console.

[Response](https://github.com/csantero/ember-sinon/issues/20#issuecomment-141991451) from @csantero, the maintainer of ember-sinon:

> Since the message is being generated from blanket, maybe you could try opening up an issue over on ember-cli-blanket.

**Comment by danny-andrews** [comment]
Can confirm: getting same console error in my project.

**Comment by jschilli** [comment]
I have tried this in both an ember-cli 1.13 and ember-cli 2.3 project and can't recreate.

is this still an issue for you? what versions (ember, ember-cli, ember-cli-blanket)?

**Comment by lolmaus** [comment]
I've switched to Browserify-backed `sinon` from npm, so I can't confirm/reject. Lets close this until someone else chimes in.
