### ISSUE TITLE
Getting this error when I dont have any tests at all. 

### ISSUE THREAD

**Issue by svkangal** [sglanzer/ember-cli-blanket#94]
TypeError: Cannot call method &#39;map&#39; of undefined<br> &nbsp; &nbsp;at Reporter.module.exports.Reporter.extend.transform (/Users/sk/screwdriver/node_modules/ember-cli-blanket/lib/reporters/lcov-reporter.js:40:38)<br> &nbsp; &nbsp;at Reporter.report (/Users/sk/screwdriver/node_modules/ember-cli-blanket/lib/reporter.js:51:21)<br> &nbsp; &nbsp;at /Users/sk/screwdriver/node_modules/ember-cli-blanket/lib/coverage-middleware.js:37:14<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/sk/screwdriver/node_modules/ember-cli/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/Users/sk/screwdriver/node_modules/ember-cli/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at /Users/sk/screwdriver/node_modules/ember-cli-blanket/node_modules/body-parser/lib/read.js:129:5<br> &nbsp; &nbsp;at invokeCallback (/Users/sk/screwdriver/node_modules/ember-cli-blanket/node_modules/body-parser/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/Users/sk/screwdriver/node_modules/ember-cli-blanket/node_modules/body-parser/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/Users/sk/screwdriver/node_modules/ember-cli-blanket/node_modules/body-parser/node_modules/raw-body/index.js:308:7)<br> &nbsp; &nbsp;at IncomingMessage.EventEmitter.emit (events.js:92:17)

**Comment by sglanzer** [comment]
I haven't tested this, but it looks like the coverageData is probably coming back empty (because of no tests) and we're expecting at least one file to be covered.  I assume the error disappears if at least one test is run?

We can absolutely add code to guard against empty data.

**Comment by svkangal** [comment]
Yes Indeed works fine with at least one test case. :+1:

**Comment by lolmaus** [comment]
I'm having the same error when doing `ember test`.

When I do `ember s` and open the tests page, everything fine, coverage gets generated. But when I run `ember test`, `coverageData` is a blank object.

How do I resolve this?

PS Using Mocha.

**Comment by sglanzer** [comment]
Check your testem file to see if it includes &coverage=true in the the test
page string

**Comment by lolmaus** [comment]
It didn't, thank you!

**Comment by jschilli** [comment]
I believe this was fixed in #111 

feel free to comment and/or reopen if not the case
