### ISSUE TITLE
Making it work with Ember-Addon

### ISSUE THREAD

**Issue by svkangal** [sglanzer/ember-cli-blanket#96]
Does this work with an ember-add-on project? Right now I have everything configured, but it doesn't seem to pick up the coverage.

**Comment by jschilli** [comment]
We use it all the time.

Note the module prefix and filter setup

```
/*globals blanket, module */

var options = {
  modulePrefix: “module-name",
  filter: "//.*module-name/.*/",
  antifilter: "//.*(tests|template).*/",
  loaderExclusions: [],
  enableCoverage: true,
  cliOptions: {
    reporters: ['json']
  }
};
```

**Comment by svkangal** [comment]
I have set it up and it does show some coverage even though I dont have any tests. Also after adding some tests it doesn't update either.
<img width="1440" alt="screen shot 2015-10-20 at 6 08 31 pm" src="https://cloud.githubusercontent.com/assets/2807160/10625238/e388448c-7755-11e5-8192-20f809c0c48f.png">

**Comment by svkangal** [comment]
Got it to work in browser but having issues on console ember test

Future versions of Ember CLI will not support v0.10.26. Please update to Node 0.12 or io.js.
version: 1.13.8
Built project successfully. Stored in "/Users/skangal/treevis/tmp/class-tests_dist-KpqDQQye.tmp".
not ok 1 PhantomJS 1.9 - Acceptance | options tab: check if options tab exists
    ---
        actual: >
            false
        expected: >
            true
        message: >
            TypeError: 'undefined' is not a function (near '...}).bind(this)).attr('class'...')
        Log: |
    ...
not ok 2 PhantomJS 1.9 - TreeVisComponent: it renders in the page
    ---
        actual: >
            null
        message: >
            Died on test #1     at http://localhost:7357/assets/test-support.js:2934
                at test (http://localhost:7357/assets/test-support.js:1826)
                at http://localhost:7357/assets/dummy.js:1197
                at http://localhost:7357/assets/vendor.js:150
                at tryFinally (http://localhost:7357/assets/vendor.js:30)
                at http://localhost:7357/assets/vendor.js:156
                at http://localhost:7357/assets/blanket-loader.js:103
                at http://localhost:7357/assets/test-loader.js:29
                at http://localhost:7357/assets/test-loader.js:21
                at http://localhost:7357/assets/test-loader.js:40
                at http://localhost:7357/assets/test-support.js:6656: 'undefined' is not a function (near '...}).bind(this)).attr('class'...')
        Log: |
    ...

**Comment by svkangal** [comment]
I think I figured out the issue.. related to PhantomJS and polyfill
