### ISSUE TITLE
Error using ember-cli-blanket with ember-cli 1.13.12

### ISSUE THREAD

**Issue by clairegrimmett** [sglanzer/ember-cli-blanket#97]
Getting the following after upgrading to ember-cli 1.13.12
Error: ENOENT, no such file or directory '/[...]/tmp/funnel-input_base_path-ynjilZ3W.tmp/0/assets/test-loader.js'

**Comment by jschilli** [comment]
@clairegrimmett did you rm -rf tmp?

**Comment by clairegrimmett** [comment]
I did.

**Comment by jschilli** [comment]
test-loader.js comes from ember-cli-test-loader (not related to ember-cli-blanket)

did you update your bower.json to the newer ember-cli-test-loader?

https://github.com/twokul/ember-cli-release-notes/blob/1cee41eb91bf7c534917fdd4cd42a1cd1a481c75/1.13.9/app/bower.json#L6

**Comment by clairegrimmett** [comment]
I have the latest version of ember-cli-test-loader. Not having any problems with the test-loader itself, the only time it has an issue is when i try to install ember-cli-blanket and run 'ember test'. Is it working for you with 1.13.12?

**Comment by jschilli** [comment]
I’m running it in an addon project with 1.13.13

no problems

**Comment by clairegrimmett** [comment]
Thanks @jschilli I managed to figure it out - it was due to our somewhat unconventional app structure that combines multiple apps into one, it was running the ember-cli-blanket postprocessTree hook more than once, which I guess used to work with 1.13.8 but now fails.
